var electrodomesticos = [
    {
        id:1,
        nombre:'Bombillo',
        icono: 'bombillo.png',
        modelos:[
            {
                m_icono:'1-1',
                modelo:'ECO LED',
                marca:'Silvania',
                consumo_diario:0.0104
            },
            {
                m_icono:'1-2',
                modelo:'',
                marca:'GE Lighting',
                consumo_diario:0.0171
            },
            {
                m_icono:'1-3',
                modelo:'Ledvance',
                marca:'Sylvania ',
                consumo_diario:0.0025
            }
        ]
    },
    {
        id:2,
        nombre:'Computadora',
        icono: 'computadora.png',
        modelos:[
            {
                m_icono:'2-1',
                modelo:'5515',
                marca:'Dell',
                consumo_diario:0.0792
            },
            {
                m_icono:'2-2',
                modelo:'5570',
                marca:'Dell',
                consumo_diario:0.0500
            },
            {
                m_icono:'2-3',
                modelo:'Aurora R13',
                marca:'Dell',
                consumo_diario:0.0875
            }
        ]
    },
    {
        id:3,
        nombre:'Estufa',
        icono: 'estufa.png',
        modelos:[
            {
                m_icono:'3-1',
                modelo:'NE63A6311SS/AA',
                marca:'Samsung',
                consumo_diario:0.2750
            },
            {
                m_icono:'3-2',
                modelo:'LREL6321S',
                marca:'LG',
                consumo_diario:0.2500
            },
            {
                m_icono:'3-3',
                modelo:'EME6063BVX0',
                marca:'Mabe',
                consumo_diario:0.2083
            }
        ]
    },
    {
        id:4,
        nombre:'Lavadora',
        icono: 'lavadora.png',
        modelos:[
            {
                m_icono:'4-1',
                modelo:'BWM7200X',
                marca:'Beko',
                consumo_diario:0.0096
            },
            {
                m_icono:'4-2',
                modelo:'WF42H5500A0',
                marca:'Samsung',
                consumo_diario:0.0108
            },
            {
                m_icono:'4-3',
                modelo:'WF42H5100A0',
                marca:'Samsung',
                consumo_diario:0.0108
            }
        ]
    },
    {
        id:5,
        nombre:'Microondas',
        icono: 'microondas.png',
        modelos:[
            /*Consumo de los microondas calculadas en base a hora de uso*/
            {
                m_icono:'5-1',
                modelo:'ML2-TC10SAIT (BS)',
                marca:'Toshiba',
                consumo_diario:1
            },
            {
                m_icono:'5-2',
                modelo:'EM036AB14',
                marca:'Black+Decker',
                consumo_diario:1
            },
            {
                m_icono:'5-3',
                modelo:'R-21LCF',
                marca:'Sharp',
                consumo_diario:1
            }
        ]
    },
    {
        id:6,
        nombre:'Plancha',
        icono: 'plancha.png',
        modelos:[
            /*Consumo de las planchas calculadas en base a hora de uso*/
            {
                m_icono:'6-1',
                modelo:'IR40V',
                marca:'Black+Decker',
                consumo_diario:1
            },
            {
                m_icono:'6-2',
                modelo:'B001RJTQ8U',
                marca:'Black+Decker',
                consumo_diario:1
            },
            {
                m_icono:'6-3',
                modelo:'D3030',
                marca:'Black+Decker',
                consumo_diario:1.6
            }
        ]
    },
    {
        id:7,
        nombre:'Secadora',
        icono: 'secadora.png',
        modelos:[
            /*Consumo de las secadoras calculadas en base a hora de uso*/
            {
                m_icono:'7-1',
                modelo:'GFD55ESSNWW',
                marca:'General Electrics',
                consumo_diario:5.6
            },
            {
                m_icono:'7-2',
                modelo:'DV22K6800EW',
                marca:'Samsung',
                consumo_diario:7.2
            },
            {
                m_icono:'7-3',
                modelo:'DVE45B6300W',
                marca:'Samsung',
                consumo_diario:7.2
            }
        ]
    },
    {
        id:8,
        nombre:'Refrigerador',
        icono: 'refrigerador.png',
        modelos:[
            {
                m_icono:'8-1',
                modelo:'WRS315SNHM',
                marca:'Whirlpool',
                consumo_diario:0.0654
            },
            {
                m_icono:'8-2',
                modelo:'CSD230SAi',
                marca:'Condura',
                consumo_diario:0.0254
            },
            {
                m_icono:'8-3',
                modelo:'CRF321SS',
                marca:'Edgestar',
                consumo_diario:0.0308
            }
        ]
    },
    {
        id:9,
        nombre:'TV',
        icono: 'tv.png',
        modelos:[
            {
                m_icono:'9-1',
                modelo:'UN65AU8000FXZA, modelo 2021',
                marca:'Samsung',
                consumo_diario:0.0354
            },
            {
                m_icono:'9-2',
                modelo:'OLED48A2PUA',
                marca:'LG',
                consumo_diario:0.0179
            },
            {
                m_icono:'9-3',
                modelo:'65UN9000AUJ',
                marca:'LG',
                consumo_diario:0.0221
            }
        ]
    },
    {
        id:10,
        nombre:'Ventilador',
        icono: 'ventilador.png',
        modelos:[
            {
                m_icono:'10-1',
                modelo:'MTCL52513AC',
                marca:'Mastertech',
                consumo_diario:0.0063
            },
            {
                m_icono:'10-2',
                modelo:'MTP2011AB',
                marca:'Mastertech',
                consumo_diario:0.0188
            },
            {
                m_icono:'10-3',
                modelo:'MTF0811AB',
                marca:'Mastertech',
                consumo_diario:0.0167
            }
        ]
    }
];